main.go

in order to avoid UDP packet loss when receiving a lot of packets on StatsD bridge.
PTAL: @juliusv

Allow configuration of UDP read buffer

---

mapper.go
mapper_test.go

It wasn't entirely clear why this wasn't allowed. We have some systems that submit metrics with their hostname in the metric. Something in the form of `test-myhost01`. This allows the mapper to match those.
Actually doesn't fully meet the use case where the name may be `test-my-host01` or something. Still working.

allow metrics with dashes when mapping

---

main.go

Adds a root endpoint similar to [haproxy exporter](https://github.com/prometheus/haproxy_exporter/blob/master/haproxy_exporter.go#L391-L398) and [node exporter](https://github.com/prometheus/node_exporter/blob/master/node_exporter.go#L179-L187)

add root endpoint with redirect

---

README.md

@juliusv Docker will fail with the current example run command.
```
$ docker run -d -p 9102:9102 -p 9125/udp:9125/udp prom/statsd-exporter
docker: Invalid hostPort: 9125/udp.
```

fix documentation for docker udp port publishing

---

exporter.go
exporter_test.go

Instead now we will send a warning message to the logs
and continue on with our day.
Also a guard has been added when we detect a channel has been
closed and the `Exporter.Listen` function will return out of
its loop vs always running. When a channel is closed there will
be no more data to consume, so this seems correct. It also allows
for a test to be written for the panic.
@juliusv @SuperQ

Don't panic when negative number counter is submitted.

---

exporter.go

Fixes https://github.com/prometheus/statsd_exporter/issues/35

Increase receivable UDP datagram size to 65535 bytes.

---

README.md
exporter.go
main.go
telemetry.go

I change the README to show all examples without the auto suffixes but mention that, for now, they still get added. I did that because I think in one of the next releases we should change the defaults: Even though it might break things, I believe all our exporters should be serve as idiomatic example which here isn't the case.

Make metric suffixes optional, expose unmapped events

---

telemetry.go

This makes the naming consistent with our best pratices.

Drop _count suffix for loaded_mappings metric 

---

bridge_test.go
exporter.go

This changeset makes statsd_exporter more tolerant of two kinds of
broken metrics.
With this changeset:
```
ERRO[0038] Bad line from StatsD: :100|ms                 source=exporter.go:357
```
With master:
```
panic: runtime error: index out of range
goroutine 1 [running]:
panic(0x86ccc0, 0xc8200100a0)
/usr/lib/go/src/runtime/panic.go:464 +0x3e6
main.escapeMetricName(0xc820109328, 0x0, 0x0, 0x0)
/home/haguenau/etc/statsd_exporter/exporter.go:191 +0xe5
main.(*Exporter).Listen(0xc820101f10, 0xc82001cba0)
/home/haguenau/etc/statsd_exporter/exporter.go:229 +0xf67
main.main()
/home/haguenau/etc/statsd_exporter/main.go:163 +0x1002
```
With this changeset:
```
ERRO[0001] Empty component on line:  foo:1|c|            source=exporter.go:388
```
With master:
```
panic: runtime error: index out of …
```

Tolerate more forms of broken lines from StatsD

---

bridge_test.go
exporter.go
exporter_benchmark_test.go
exporter_test.go

This would prevent an incident I have been seeing:
The exporter will happily store metrics with invalid utf8 in labels. Prometheus will then try to collect them and will choke on invalid utf8, [here](https://github.com/prometheus/prometheus/blob/e83f05fe93c32c9e808b2a6a907337b442a540dc/vendor/github.com/prometheus/common/model/labels.go#L157) and [here](https://github.com/prometheus/prometheus/blob/dc4d5fef2a75b9b4e5124fe41ec291eda52f667e/vendor/github.com/prometheus/common/expfmt/decode.go#L104) I think. The statsd-exporter target will be  marked down because of this error.
I wonder if the `utf8.ValidString` check for every input line would make StatsD ingestion considerably slower/increase CPU usage?
I've tried to only check DogStatsD tag values first, but it wasn't enough and it was …

Skip metrics with invalid utf8

---

main.go

ListenAndServe shouldn't fail silently in self goroutine, now it calling log.Fatal

ListenAndServe now fails on exit

---

mapper.go
mapper_test.go

Issue #55 shows that the mapping config is not parsed in full if a terminating newline is missing. The last metric mapping is not parsed at all and no errors are shown. This PR changes the parsing method by treating the last line of the file as if it would be a newline between two mappings.
Added two new testcases to `mapper_test.go`:
- a single mapping configuration without a terminating newline
- two mapping configurations without a terminating newline
Tested by running `go test` and it gives a big thumbs up. In addition I tested this locally by running `prom/statsd-exporter` (Dockerhub) and the fixed version side-by-side with this mapping:
```
*.test.*
name="test"
foo="$1"
bar="$2 <no newline>
```
Results for the official image:
```
$ curl -s 127.0.0.1:9102/metrics | grep …
```

Improve mapping configuration parser

---

bridge_test.go
exporter.go

Added support for sampling rate in timings. This will for instance accept the statsd line
```
object-server.REPLICATE.timing:0.500917434692|ms|@0.1
```
The above line is real and was sent by openstack swift in our environment.
When a timing event with a sample rate set is received, it will be cloned a number of times in order to simulate it being received without a sampling rate set. This is kind of a dirty hack, but I think that it should be fine in practice.

Added support for sampling factor on timing events

---

exporter.go
telemetry.go

This PR contains the fixes for #63 
I've left them as separate commits for easier review, if preferred I can squash these as well.
cc: @grobie

Fixes for crashes with conflicting metric values

---

bridge_test.go
exporter.go
exporter_benchmark_test.go
exporter_test.go
main.go

support TCP StatsD, on port 9125

add TCP StatsD listener support

---

exporter.go
exporter_test.go

Convert milliseconds to seconds before passing into prometheus_client histogram

Resolves #88 - histograms use wrong units

---

exporter.go

* Reduced all `log.Error*` events to `log.Debug*` in `exporter.go` where
an existing internal metric tracks the event.

Resolves #81 - Reduce log levels

---

README.md
exporter.go
exporter_test.go
main.go

As mentioned in discussion on #77 this flag has been deprecated in spirit by the documentation's strong recommendation against using it. Additionally there is a strong distaste for having global boolean flags.
* Remove option flag
* Update NewExporter call signature to not take suffix boolean
* Update tests to reflect new behavior and signature
* Update documentation to reflect option flag removal

Removes `-statsd.add-suffix` option flag

---

README.md
mapper.go
mapper_test.go
match.go

* Added `regex` match_type as valid config callout in both individual mappers
and mapper defaults
* Added test coverage for changes
* Updated documentation to reflect usage of `match_type` parameter and
provide example of a raw regex match rule

Resolves #84 adds support for regex mappers

---

README.md
exporter.go
mapper.go

* Updated mappings to accept custom help text in YAML config
* Updated exporter to display configured help messages
* Update README to reflect aditional configurability
* Minor Update to exporter to allow tests to pass with mocked
statsdlistener that has no mappers

Resolves #78 Allow help text to be customized

---

exporter_test.go

Travis CI [does not have IPv6][0] in any environment. It could be
[enabled][1] if we ran the build in a VM, but that is much slower to
start. Instead, we just force the test connection to use IPv4.
[0]: https://blog.travis-ci.com/2015-11-27-moving-to-a-more-elastic-future#ipv6-no-longer-present
[1]: travis-ci/travis-ci#5200 (comment)

Fix TravisCI tests: Force IPv4 for the mock TCP listener

---

exporter.go
telemetry.go

The "packets" metric had heavily overloaded meaning for different
"outcomes", and would often be incremented multiple times, sometimes
even with a single (per-line) increment in one outcome corresponding to
multiple increments in another.
This removes the broken metric, and replaces it with separate total and
error counters for each level of processing. This allows monitoring the
network traffic handled separately from the samples incurred by it.
Supersedes #54 based on the discussion there.

Break out the telemetry during sample processing

---

README.md

According to the project's naming best practices[0], the suffix to
indicate a counter type is called `_total`.
[0]: https://prometheus.io/docs/practices/naming/

Use _total suffix for counters

---

mapper.go
mapper_test.go

Fix the test for bad regexes:
This test did not fail because the regex was bad, it failed because yaml
parsing failed.
This fixes the yaml which uncovers a panic in initFromYAMLString.
Avoid panic from compiling user supplied regex:
If an invalid regex is supplied mustCompile would panic during
configuration reload. Return an error instead that can be handled.

Avoid regex panic

---

README.md
exporter.go
mapper.go
mapper_test.go
metric_type.go

StatsD allows emitting different metric types under the same metric name, but the Prometheus client library can't merge those. For those use-cases the mapping definition now allows you to specify which metric type to match.
Resolves: #63

Allow mapping match on metric type

---

README.md
exporter.go
mapper.go
mapper_test.go

* Quantile values for a Summary are now configurable.
* The default quantiles (DefObjectives) in the Prometheus Go client library is
deprecated. This commit removes the reliance on it.

feat: configurable quantiles for Summaries

---

pkg/mapper/fsm/fsm.go
pkg/mapper/mapper_test.go

In some use case that the mapping rules need backtracking and the
non-matched rule has star(s), the fsm will incorrectly return the
captures from latter non-matched rule.
This PR fixes this by copying the current `captures` slice to a different
slice and only return the copied slice. So that later assignment to
`captures` won't affect the captures of a previously matched rule.
Fix #168

fix: don't let captured fields being overwritten by backtracking

---

README.md
exporter.go
exporter_test.go
go.mod
pkg/clock/clock.go
pkg/mapper/mapper.go
pkg/mapper/mapper_test.go

This patch implements clearing of metrics with variable labels with per-mapping configurable timeout (ttl). Our monitoring installation is suffered from the behavior desribed in #129. There are metrics from Kubernetes pods with constantly changing values for labels. For example, metric `ingress_nginx_upstream_retries_count` with label `pod` and changing pod name as a value for this label. There is no sense to store metrics with old pod names as they are never repeated. Removing metrics with this stale values will not cause any damage to subsequent aggregations or multiple prometheus servers.
The patch is divided by 3 parts to simplify a review:
- replace Metrics with Collectors to gain ability of deletion metrics. So Elements in CounterContainer stores CounterVecs instead of Counters.
- …

Remove stale metrics

---

exporter.go
exporter_test.go

Fixes #177 
EDIT: Oh bleh, I'll actually pull and build and ensure this works, and not rely on CI

Scale summaries from milliseconds to seconds.

---

Dockerfile

What this PR does / why we need it:
Adds a healthcheck for checking the status of the metrics endpoint. 
Which issue(s) this PR fixes : This will help us recover in sitiuations like getting Internal Server Error and the container being up. 
@matthiasr Please review this. Thanks!

Adds healthcheck for checking the status of the container

---

exporter.go
exporter_test.go
telemetry.go

Avoids crashing when escaping empty metric names.
The metrics are ignored and a message is logged. 
@matthiasr

Fixes #191: crash on empty metric name

---

exporter.go
telemetry.go

As discussed in #160 
Add `statsd_exporter_events_actions_total` which is event count by mapper action. Unmapped events are not counted.

Add metric for count of events by action

---

exporter.go
exporter_test.go

While investigating something else,I did some profiling and found that `escapeMetricName` took a large amount of processing time. The regex was the majority of this time.  `escapeMetricName` is called on every event processed. 
The valid set of characters for a metric name is fairly small, so we can optimize this a bit.  I replaced the regex in escapeMetricName with a loop over the runes.  I originally used a `strings.Builder` to build the output, but building the string manually provided to be much faster.
This passes tests, but I am sure I am missing something obvious. This is borderline unreadable as well and needs some comments. I did this on a sick day, so I do not trust myself on this. 
For benchmarks, see https://gist.github.com/bakins/f4d342d1cc93f4911ffd4efa9d93ecab

Increase escapeMetricName performance

---

exporter.go
telemetry.go

Currently, we track the number of mappings, but not the unique metricNames.  This adds a simple counter to track the count of metricName+labelNames.  If this number increases significantly, then the application sending metrics may be misbehaving.  This does not count unique label values.
I didn't see a way to get this in the current metrics, so please let me know if there is an existing way to get this information.

Add metric to track unique metric names the exporter is tracking

---

Dockerfile

Run statsd_exporter as `nobody`.
Closes: https://github.com/prometheus/statsd_exporter/issues/201
Signed-off-by: Ben Kochie <superq@gmail.com>

Don't run docker container as root

---

exporter.go
main.go
telemetry.go

Implement listener for Unixgram sockets

---

exporter.go
exporter_test.go

Currently the exporter will only report sum/count metrics for summaries if a mapping file isn't defined rather than a default set of quantiles.
This fixes #195.
@matthiasr

Add default quantiles for summaries if no mapping file exists

---

exporter.go
exporter_test.go

Profiling shows that for our environment, parsing tags is the single biggest steady state contributor to CPU usage.  This PR replaces some calls to strings library functions to simpler implementations with the intention of reducing CPU overhead and some memory allocations.  
Here is an example of the before scenario:
```
$ time go test -bench=BenchmarkParseDogStatsDTagsToLabels -test.benchmem -benchtime 60s
goos: darwin
goarch: amd64
pkg: github.com/prometheus/statsd_exporter
BenchmarkParseDogStatsDTagsToLabels/1_tag_w/hash-8              300000000              319 ns/op             392 B/op          6 allocs/op
BenchmarkParseDogStatsDTagsToLabels/1_tag_w/o_hash-8            300000000              318 ns/op             392 B/op          6 allocs/op …
```

Tag parsing optimizations

---

README.md
bridge_test.go
exporter.go

This adds the ability to accept Datadog's distribution type and treat it like a histogram/summary.

Add support for Datadog distribution type

---

exporter.go
exporter_test.go

This adds sanity checking before registering a metric to ensure that the metric isn't already registered under an existing name.  This prevents the exporter from getting into a state where it has accepted and registered conflicting metrics, and then cannot report the metrics it has collected.
I believe this should address the issues raised in #186

Add checking for conflicting metrics

---

README.md
exporter_test.go
go.mod
go.sum
main.go
pkg/mapper/mapper.go
pkg/mapper/mapper_benchmark_test.go
pkg/mapper/mapper_cache.go
pkg/mapper/mapper_test.go
vendor/github.com/hashicorp/golang-lru/.gitignore
vendor/github.com/hashicorp/golang-lru/2q.go
vendor/github.com/hashicorp/golang-lru/LICENSE
vendor/github.com/hashicorp/golang-lru/README.md
vendor/github.com/hashicorp/golang-lru/arc.go
vendor/github.com/hashicorp/golang-lru/doc.go
vendor/github.com/hashicorp/golang-lru/go.mod
vendor/github.com/hashicorp/golang-lru/lru.go
vendor/github.com/hashicorp/golang-lru/simplelru/lru.go
vendor/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
vendor/modules.txt

Mapping is one of the most expensive operations done, but throwing a cache in front of it is an easy way to reduce that pain.
Alongside that, updating the config invokes a lock and wipes the cache, and on k8s if your config is a configmap, it will be regularly synced into the container (even with no changes), at which point you will get needless config reloads (which now wipes the cache, just to be safe). Only reloading if the sha changes is a good way to keep the cache around as long as possible.
Here's the benchmark results:
```
BenchmarkGlob10Rules-12                                 	 5000000	       258 ns/op
BenchmarkGlob10RulesCached-12                           	20000000	        71.8 ns/op
BenchmarkRegex10RulesAverage-12                         	 1000000	      1134 ns/op …
```

Adding mapping cache

---

exporter.go
exporter_test.go

While it doesn't report it as a metric, when collecting, the registry considers the base metric name to belong to the histogram that's registered.  This means that we need to prevent other metrics from
registering anything under this name, in addition to checking for the `_bucket`, `_sum` and `_count` suffixes.
This was missed in #213

Check for histogram conflict on main name

---

exporter.go

This converts `escapeMetricName` to use `strings.Builder` instead of allocating a byte array, filling it and then converting it to a string. This also optimizes for the case where the metricName is already valid, and in that case, it just returns the original string.
This reduces memory allocations from 2 per call to 1 per call in the case when the string does need to be escaped, and reduces it to zero memory allocations when the string is already valid.
As discussed in #197, `escapeMetricName` is called a *lot*, and even after the improvements there, we still see this pretty far up the list in terms of cpu usage in profiling.
Benchmark before:
```
$ go test -benchmem -run=^$ github.com/prometheus/statsd_exporter -bench '^(BenchmarkEscapeMetricName)$' -benchtime 30s
goos: darwin
goarch: …
```

Convert escapeMetricName to use strings.Builder

---

bridge_test.go
exporter.go

This converts the byte buffer to a string by casting and parses the
string by looping over it instead of calling Split.
This usage of unsafe is taken from the strings.Builder package here:
https://github.com/golang/go/blob/cb5c82bc3df2e95c2ab36555fefb7cd3f334c685/src/strings/builder.go#L47
This also adds a benchmark for testing overall performance of the UDP code path.
Signed-off-by: Clayton O'Neill <claytono@github.com>

Reduce memory allocations in handlePacket

---

exporter.go
exporter_test.go

Previously we were sorting labels in every container to build a map key, but also when generating the hash key by calling the `LabelsToSignature` method.  This moves the sorting to be done early in the event processing then passes the sorted label array around.
Before:
```
$ /usr/local/bin/go test -benchmem -run=^$ github.com/prometheus/statsd_exporter -bench '^(BenchmarkHashNameAndLabels)$' -benchtime 5s
goos: darwin
goarch: amd64
pkg: github.com/prometheus/statsd_exporter
BenchmarkHashNameAndLabels/no_labels-8          300000000               26.7 ns/op             0 B/op          0 allocs/op
BenchmarkHashNameAndLabels/one_label-8          50000000               163 ns/op              48 B/op          2 allocs/op
BenchmarkHashNameAndLabels/many_labels-8        10000000               889 …
```

Optimize label sorting

---

exporter.go

Hi.
I've faced issue with latest statsd version: `Failed to update metric "asr_duration". Error: inconsistent label cardinality: expected 0 label values but got 4 in prometheus.Labels`
It happened after this commit https://github.com/prometheus/statsd_exporter/commit/d143398343bc68ba149e51bdd84acf6e679118fd 
Basically we sort prometheus labels (https://github.com/prometheus/statsd_exporter/blob/master/exporter.go#L461) before fill structure (https://github.com/prometheus/statsd_exporter/blob/master/exporter.go#L470)
Fixes issue for me, also rollback to v0.9.0 fixes it.

Fix inconsistent label cardinality error

---

pkg/mapper/mapper.go
pkg/mapper/mapper_cache.go

- Statsd allows users to provide a metric with the same name but
differing types (counter, gauge, timer)
- The exporter allows this by letting users specify a
"match_metric_type" in the mapping config
- However the mapper cache does not look at the metric type so it would
return a MetricMapperCacheResult for the type of the first metric with
that name that the exporter saw
- Add MetricType to the signature for the cache and format the metric
name with the type to provide unique keys for a metric with the same
name but differing type
Fixes #228

Make mapper cache respect metric type

---

README.md
bridge_test.go
event.go
event_test.go
exporter.go
exporter_benchmark_test.go
exporter_test.go
main.go
telemetry.go

At high traffic levels, the locking around sending on channels can cause a large amount of blocking and CPU usage.  This adds an event queue mechanism so that events are queued for short period of time, and flushed in batches to the main exporter goroutine periodically.
The default is is to flush every 1000 events, or every 200ms, whichever happens first.

Add internal event queuing and flushing

---

main.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_1_8.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_pre_1_8.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client_1_8.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
vendor/modules.txt

client_golang's `http` is [deprecated](https://github.com/prometheus/client_golang/blob/8d9c21f0cf5f73718ee86bb3a8e6432b88e9291d/prometheus/http.go#L52) in favor of `promhttp`.
This should fix #80 
Tagging @matthiasr

Use promhttp instead of http

---

pkg/mapper/mapper_test.go

Required three minor modifications to this test pattern:
- Couldn't keep using a map, as we needed duplicate entries in the data structure
- Added support for an explicit `metricType`, for when you care about that.
- Enabled the mapping cache to better simulate "real world" scenarios
Here's my test results from pre and post #229:
```
$ go test
WARN[0000] backtracking required because of match "backtrack.*.bbb", matching performance may be degraded  source="fsm.go:313"
WARN[0000] backtracking required because of match "*.dummy.*", matching performance may be degraded  source="fsm.go:313"
WARN[0000] match "order.*.*" is a super set of match "order.*.bbb" but in a lower order, the first will never be matched  source="fsm.go:294"
WARN[0000] match "test.foo.*" is a super set of match …
```

Add test for multiple explicit metric types.

---

main.go

When sending data with TCP exporter was panicking.
```
echo "foo_bar:1|c" | nc localhost 9125
```
```
INFO[0000] Starting StatsD -> Prometheus Exporter (version=, branch=, revision=)  source="main.go:168"
INFO[0000] Build context (go=go1.12.4, user=, date=)     source="main.go:169"
INFO[0000] Accepting StatsD Traffic: UDP :9125, TCP :9125, Unixgram   source="main.go:170"
INFO[0000] Accepting Prometheus Requests on :9102        source="main.go:171"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1491d98]
goroutine 14 [running]:
main.(*StatsDTCPListener).handleConn(0xc000146ac0, 0xc000010048)
/Users/selman/src/statsd_exporter/exporter.go:514 +0x208
created by main.(*StatsDTCPListener).Listen …
```

add missing eventHandler to StatsDTCPListener

---

README.md

They can start with a * which makes YAML barf if not quoted. Instead of
figuring out individually what does and does not need to be quoted,
always quote.
Signed-off-by: Matthias Rampke <mr@soundcloud.com>

Quote all matchers in YAML examples

---

registry.go

Fixes a bug where setting the TTL parameter would periodically remove time series.
The reason for this was that the 'lastRegisteredAt' element was only set at creation of the time series, and not updated every time a new event was received for that time series.
__Maintainer:__ (@matthiasr)

Fix TTL bug

---

event.go

We send the slice off to be process, but potentially start overwriting
the previous content straight away. Just start again with a fresh slice.
Fixes #247

Event queue processes and filling race.

---

README.md

DogStatsD by default emits timer metric in seconds, while the exporter assumes milliseconds; which is the default for statsd. The `use_ms` option fixes this, and will be useful for dogstatsd users to know.

Add note about DogStatsD `use_ms` option

---

README.md

While rolling out `statsd exporter`, this is one of the things that confused me. What's the final unit of the exported metric when I am querying prometheus? I took a look at the code to clarify, so thought adding this in the documentation is a good idea. 
Please take a look.

README - Add a note regarding unit conversions for timers

---

README.md
bridge_test.go
exporter.go
exporter_test.go

Add support for Librato-style tags. These appear in the metric name rather than as a separate field, ala:
```
metric.name#tag=val,tag2=val2:0|c
```
Maybe this is just scratching my itch, but I'm facing the impossibility of attempting to incrementally move from Librato (and librato tags) to an internal Prometheus server. The only way forward for me is to either heavily hack the original Statsd server and the Librato backend plugin to support DogStatsD tags, or to add a bit of support to this exporter, which is what I've opted to do.
This is a fairly straightforward implementation, and is almost entirely backwards compatible, so I didn't bother to invoke the mailing list. The only place this might break is if someone is already using metrics with hash signs in them -- but this should …

Add librato tag support

---

README.md

Only `key:value` format for dogstatsd is accepted by latest version of statsd exporter.
I've tried both official client and bash scripts to send the data:
echo "newpure.test:1|c|@0.5|#country:china" | nc -w 1 -u 127.0.0.1 9125` - will work
echo "newpure.test:1|c|@0.5|#country=china" | nc -w 1 -u 127.0.0.1 9125 - will not work

Fix format for dogstatsd tags

---

pkg/mapper/mapper_cache.go

While doing some profiling for something else, I noticed `fmt.Sprintf` in the hot path for cache operations. Changing this to string concatenation gives some improvement in performance.
benchmarked using `go test -bench=BenchmarkGlob100RulesMultipleCapturesCached -benchtime=10s -benchmem`
output from benchcmp:
```
benchmark                                          old ns/op     new ns/op     delta
BenchmarkGlob100RulesMultipleCapturesCached-12     280           158           -43.57%
benchmark                                          old allocs     new allocs     delta
BenchmarkGlob100RulesMultipleCapturesCached-12     4              2              -50.00%
benchmark                                          old bytes     new bytes     delta
BenchmarkGlob100RulesMultipleCapturesCached-12 …
```

mapper cache: Use string concatenation rather than Sprintf for formatKey

---

pkg/mapper/mapper_cache.go

Add metrics to record mapper cache hits and total gets.

mapper cache: Add cache metrics for total gets and hits

---

pkg/mapper/mapper_cache.go

The mapper package can be used outside the statsd exporter, so it is
better to use generic names here.
follow-up to #280

Rename mapping cache length metric

---

pkg/mapper/mapper.go
pkg/mapper/mapper_test.go

Fixes https://github.com/prometheus/statsd_exporter/issues/273
Make shallow copy of FSM result so that we do not overwrite name.
Before shallow copy:
```
$ go test -v -run='^(TestMultipleMatches)$' ./pkg/mapper/
=== RUN   TestMultipleMatches
--- FAIL: TestMultipleMatches (0.00s)
mapper_test.go:936: 1:1 Expected name aa_bb_dd_total, got aa_bb_cc_total
FAIL
FAIL	github.com/prometheus/statsd_exporter/pkg/mapper	0.260s
FAIL
```
After shallow copy:
```
$ go test -v -run='^(TestMultipleMatches)$' ./pkg/mapper/
=== RUN   TestMultipleMatches
--- PASS: TestMultipleMatches (0.00s)
PASS
ok  	github.com/prometheus/statsd_exporter/pkg/mapper	(cached)
```

Use correct name when multiple names match same FSM match

---

main.go

We were already passing it to the TCP and Unixgram listener, but
somehow left it out of the UDP listener setup.
Fixes #285.
cc @brianirish @yclybouw

Pass logger to UDP listener

---

exporter.go
exporter_test.go
pkg/mapper/escape.go
pkg/mapper/escape_test.go

https://github.com/prometheus/statsd_exporter/issues/234#issuecomment-501206903
I've copy pasted this into multiple personal projects as well, so let's export this.
We could integrate it more into mapping later.

Move escapeMetricName to mapper

---

README.md
pkg/mapper/mapper.go
pkg/mapper/mapper_test.go
registry.go

The Go client for prometheus aggregates summary metrics over 10
minutes by default, in 5 buckets.  This is not always the behaviour we
want.
Allow tweaking those settings in `statsd_exporter`, so we can
aggregate summary metrics over more or less time, with more or fewer
buckets, and set the cap for the bucket as well.
/cc @matthiasr

allow setting granularity for summary metrics

---

main.go
pkg/mapper/mapper.go
pkg/mapper/mapper_benchmark_test.go
pkg/mapper/mapper_cache.go

Add a simple random replacement cache based on a map.
Add command line flag to choose mapper cache type, defaulting to existing lru cache.
In the case that all entries fit into the cache, this new cache is faster as it uses a read lock for gets and also has less bookkeeping than the lru cache.
In the case that all entries do not fit into cache, the random replacement cache can avoid thrashing the cache. In some cases, the lru cache will have a very low hit ratio as it is constantly evicting entries.  Our use case is a huge number of unique metric names in "old" statsd format that we map to relatively few Prometheus metrics.
Note: I realize this is probably a much larger change than we may want all at once, but wanted to get feedback on the approach, etc. 
Benchmark results:
```
go test …
```

Add random replacement mapper cache 

---

README.md

specifically, deny compatibility guarantees, but do note that we
recognize the packages as reusable.
Signed-off-by: Matthias Rampke <mr@soundcloud.com>

Add notes about library usage to the README

---

README.md
main.go

If desired, go through all the motions of setting up the exporter, but
then exit. This is not very elegant, as we actually open the ports,
which may not be what you want to do in a pipeline, but it is the
quickest way to implement this.
Fixes #263.

Support checking configuration and exiting

---

bridge_test.go
exporter_benchmark_test.go
pkg/event/event.go
pkg/exporter/exporter.go
pkg/exporter/exporter_test.go
pkg/line/line.go
pkg/mapper/fsm/README.md
pkg/mapper/mapper.go
pkg/mapper/mapper_defaults.go
pkg/mapper/mapper_test.go
pkg/mapper/mapping.go
pkg/mapper/metric_type.go
pkg/mapper/observer.go

This fixes #307 by moving millisecond-->second conversion to the buildEvent function for `ms` statTypes and also adds a case for `h` and `d` statTypes without the conversion. This effectively makes the TimerEvent value in seconds/unitless. Since this is no longer just limited to timers, should the TimerEvent be renamed to DistributionEvent or something similar? 
Test cases were also added for the three distribution types and the conversions.
Summary:
`ms` units in milliseconds, converted to seconds for prometheus
`h` no units, no conversion
`d` no units, no conversion
The benchmark tests were broken, so the metrics were added back to them to get the benchmark working. That commit can be removed if necessary.
Before:
```
$ go test -bench=.
goos: darwin
goarch: amd64
pkg: …
```

[307] Add support for histograms and distributions without unit conversion

---

pkg/mapper/mapper.go
pkg/mapper/mapper_test.go

They are valid. Fixes #256.
@mizhka is this what you meant?

Allow single-letter components in metric names

---

pkg/event/event.go

I noticed there were a few things that didn't get renamed, so I changed them for consistency. No functional change
@matthiasr

rename events for consistency

---

bridge_test.go
exporter_benchmark_test.go
line_benchmark_test.go
pkg/line/line.go

Adds parsing for SignalFX-style tagsand a benchmark for LineToEvents. Fixes #268. It's unclear from the signalfx docs, but it appears that the tags can exist anywhere in the name field, making parsing a little more complicated.
There is a definite slight cost to parsing these tags since they can be in the middle of the name, and have opening and closing runes.
Before:
```
go test -bench='BenchmarkLineToEvents(1|5|50)'                                                                                                                
goos: darwin
goarch: amd64
pkg: github.com/prometheus/statsd_exporter
BenchmarkLineToEvents1-12         148065              7847 ns/op
BenchmarkLineToEvents5-12          30534             39436 ns/op
BenchmarkLineToEvents50-12          3038            392718 ns/op …
```

[268] Support SignalFx Tags

---

exporter_benchmark_test.go
line_benchmark_test.go

Modify benchmarks to not measure startup costs - https://dave.cheney.net/high-performance-go-workshop/dotgo-paris.html#avoiding_benchmarking_start_up_costs
This doesn't seem to affect the benchmark results too much, but seems more correct.
@matthiasr

improve benchmark validity by not measuring startup costs

---

line_benchmark_test.go

This breaks out the line benchmarks by format, only tests one line per iteration so that the benchmark results reflect the time taken to parse one line, and always reports allocations for the line benchmark.  This should make it easier to spot changes in line parsing.
```
$ go test -bench=BenchmarkLineToEvents. 
goos: darwin
goarch: amd64
pkg: github.com/prometheus/statsd_exporter
BenchmarkLineToEventsMixed1-12                    143725              8279 ns/op            4778 B/op         91 allocs/op
BenchmarkLineToEventsMixed5-12                     30028             40079 ns/op           23892 B/op        455 allocs/op
BenchmarkLineToEventsMixed50-12                     2978            403951 ns/op          238924 B/op       4550 allocs/op
BenchmarkLineToEventsStatsd-12 …
```

break out line benchmarks by format

---

pkg/registry/registry.go

Well, it doesn't change any behaviour because `prometheus.Gauge` implements `prometheus.Counter` and the conversion works also fine.
But it'd better that we fix this by using `prometheus.Gauge` for `gauge`.

Use prometheus.Gauge interface instead of prometheus.Counter

---

pkg/address/address.go
pkg/registry/registry.go

The error strings shouldn't be capitalized as it's considered a good practice. Because if look up the function call stack, then the function using that error message won't like if the string is capitalized.
Also, now it matches the format as the other error strings (i.e., not capitalized) present in the codebase.

Error strings shouldn't be capitalized 

---

pkg/registry/registry.go

This PR fixes the case when the metric is not present in `rm` (registered metric) then `LastRegisteredAt` and `TTL` are initialized twice. Firstly, `LastRegisteredAt` is initialized with the `time.Time`'s zero value and then with `clock.Now()`. Plus, `TTL` is initialized with the same value twice.

Avoid double initialization of variables

---

bridge_test.go
exporter_benchmark_test.go
main.go
pkg/exporter/exporter.go
pkg/exporter/exporter_test.go
pkg/mapper/mapper.go
pkg/mapper/mapper_cache.go
pkg/registry/registry.go

Importers of pkg/exporter may not want for series to be imported into the default registry. This PR makes it possible to provide a custom registry for metrics registration.
Signed-off-by: Robert Fratto <robertfratto@gmail.com>

Pass around custom registry for registering exporter metrics

---

pkg/listener/listener.go

Allows other implementations of the parser for projects that reuse much of statsd_exporter. I'm using a custom format, but https://github.com/prometheus/graphite_exporter could possible use this as well.

Use a Parser interface to allow alternate implementations

---

main.go

This moves the logic pertaining to setting up listeners after the exporter is created and the `checkConfig` (#263) early exit is evaluated.
In a CI setting, where the goal is to validate the config, setting up listeners seems unnecessary and presents opportunities for unrelated build failures.
I tested a number of startup configurations and I don't believe this breaks anything.
@matthiasr

Refactor startup order to not grab ports when checkConfig is true

---

README.md

Note that regular expression matches are only evaluated after glob
matches. Add headings and introductory sentences to each glob type.
Remove the technical reasoning for choosing glob vs. regex; instead
explain the performance implications and gotchas of each type in turn.
Closes #349.
@faja does this clarify things for you?

Reorder and rework glob vs. regex documentation

---

README.md
pkg/exporter/exporter.go
pkg/mapper/mapper.go
pkg/mapper/mapper_defaults.go
pkg/mapper/mapper_test.go
pkg/registry/registry.go

The first PR got too complex as I found other little edge cases. This should be a simpler version.
This allows setting histogram_options and summary_options in the defaults section. I added some tests and refactored the mapper tests to use named subtests, but I still want to test it more thoroughly before I mark this as ready.
Feedback appreciated.
Fixes #336 @matthiasr

Allow setting defaults for histogram and summary options

---

README.md

In double-quoted strings, the backslash is [special to YAML](http://blogs.perl.org/users/tinita/2018/03/strings-in-yaml---to-quote-or-not-to-quote.html).
Make sure that the examples do this correctly.
Fixes the wonky rendering on github.com.
Fixes #371.

Escape backslashes in regex examples

---

.gitpod.Dockerfile
.gitpod.yml
CONTRIBUTING.md

This commit implements a fully-automated development setup using Gitpod.io, an
online IDE for GitLab, GitHub, and Bitbucket that enables Dev-Environments-As-Code.
This makes it easy for anyone to get a ready-to-code workspace for any branch,
issue or pull request almost instantly with a single click.
Similar to prometheus/prometheus#7749.

Add configuration for Gitpod

---

pkg/mapper/mapper.go
pkg/mapper/mapper_test.go

Fixes #328 
Rework metricLineRE to support matching segments that start with a number. I'm not entirely sure that this is the exact use case, or that the tests duplicate the issue that @rayjcwu was describing, but it seems to work. The full regex used for matching glob patterns is below, and I think valid, but please double check. 
```
^(\*|[a-zA-Z_](-?[a-zA-Z0-9_])*)(\.\*|\.[a-zA-Z0-9_](-?[a-zA-Z0-9_])*)*$
```
The only other difference I think this change makes is that now `*` is valid , whereas previously I think it would have failed - is that in spec?
@matthiasr

Support metric name segments starting with numbers

---

go.mod
go.sum
pkg/mappercache/lru/lru.go

Addresses https://github.com/prometheus/statsd_exporter/issues/362
Use a simple wrapper around groupcache LRU cache.

Use groupcache for LRU cache

---

main.go
pkg/exporter/exporter.go
pkg/level/level.go
pkg/level/level_test.go
pkg/line/line.go
pkg/listener/listener.go
pkg/mapper/fsm/fsm.go
pkg/mapper/mapper.go

filter log calls by log level
Fixes #384

replace level pkg

---

README.md
main.go
pkg/listener/listener.go
pkg/relay/relay.go

Add a simple statsd packet output relay that buffers and forwards raw
statsd lines.
* Only supports UDP output.
* Has a hard-coded buffering timeout of 1 second.
https://github.com/prometheus/statsd_exporter/issues/95
Signed-off-by: SuperQ <superq@gmail.com>

Add statsd relay

---

main.go
pkg/relay/relay.go

Add some metrics to the statsd relay.
* The number of StatsD packets relayed.
* The number lines that were too long to relay.
Also convert main.go to use promauto for metric registration.
Signed-off-by: SuperQ <superq@gmail.com>

Add metrics to relay

---

pkg/registry/registry.go

Allowing the usage of the instance for these options. For the Grafana Agent this is preventing certain types of stats from being pushed. @matthiasr

Use the instance registry instead of the prometheus.registry

---

Dockerfile

When in k8s, container has `runAsNonRoot` policy and image has non-numeric user (nobody), then the deployment will fail as it cannot verify user is non-root.
Closes #406
Signed-off-by: Aleksandr Vinokurov <aleksandr.vin@gmail.com>

Set numeric user to comply runAsNonRoot k8s policy

---

.circleci/config.yml

To get off the [deprecated] circleci/golang.
Fixes #424.
[deprecated]: https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034

Switch to cimg/go for build+test

---

go.mod
go.sum
pkg/relay/relay.go
pkg/relay/relay_test.go

I am adding a new metric to address issue #427, it counts how many lines were buffered to be relayed.
- Adding new simple test to relay package
- Adding new metric to relay struct
- Adding new test section to check on metrics
- Adding license headers on file

New metric for relayed lines

---

pkg/mapper/mapper_benchmark_test.go

During an investigation of resource usage in a branch of mine I noticed we
have broken benchmark for BenchmarkGlobNoOrderingWithBacktracking.
This is the only benchmark that needed the logger and it was breaking because
we were not passing a logger to the MetricMapper.

Fixing broken benchmark for mapper

---

pkg/relay/relay_test.go

Fixes flaky test #443  using `runtime.Gosched()` to allow other goroutine to receive from buffer.

fix flaky test gosched hack

---

pkg/mapper/mapper.go

`ioutil` is deprecated from go1.16 (ref: https://go.dev/doc/go1.16#ioutil).
So removed them.
Signed-off-by: inosato <si17_21@yahoo.co.jp>

Remove ioutil

---

pkg/mapper/mapper.go

The FSM backtracking detection issues a log line. Make sure there is a
non-nil logger before doing that.
Avoids the crash in prometheus/graphite_exporter#197.

mapper: Make sure we have a logger before backtracking check

---

main.go

The default behavior of kingpin lib is to print stuff to stderr. This is now changed by using the os.Stdout writer. Now information like version and help text will be printed to stdout.

Print version, help etc to stdout

---

README.md
pkg/mapper/mapper.go
pkg/registry/registry.go

As of client_golang 1.14+ we have support for sparse histograms. This will start to pave the way to allow the exporter not to need bucket configuration per metric anymore.
On top of that, the current behavior is that buckets are still used in the text exposition format, and only when protobuf is negotiated the new native histograms are used, so it should be safe to upgrade right now without changes for older version of prometheus.

Update client_golang to enable native histograms

---

README.md

The origin link was 404, replace it with GitHub SignalFx-agent readme

Fix signalfx tag doc link

---

pkg/mapper/mapper.go
pkg/mapper/mapper_defaults.go
pkg/mapper/mapper_test.go
pkg/mapper/mapping.go

This is making the `mapperConfigDefaults` and  `metricObjective` structs inside `MetricMapper` object public, so that Grafana Agent or any other application embedding this exporter can instatiate `MetricMapper` without using the `InitFromYAMLString` directly.
This is really helpful when you are not defining your configuration using YAML standard.

Making mapperConfigDefaults public

---

README.md
pkg/exporter/exporter.go
pkg/exporter/exporter_test.go
pkg/mapper/mapper_test.go
pkg/mapper/mapping.go

Fixes https://github.com/prometheus/statsd_exporter/issues/498
This field allows configuring unit conversions in mappings. This is important for following [prometheus best practices](https://prometheus.io/docs/practices/naming/), which states that metrics should use base units (e.g. seconds, not milliseconds). For example:
```yaml
mappings:
- match: foo.latency_ms
name: foo_latency_seconds
scale: 0.001
- match: bar.processed_kb
name: bar_processed_bytes
scale: 1024
```

Add `scale` field to mapping config

---

bridge_test.go
exporter_benchmark_test.go
main.go
pkg/exporter/exporter_test.go
pkg/listener/listener.go

In this PR I am introducing a queue for raw statsd udp payloads and a worker to process them in another goroutine
As discussed in https://github.com/grafana/k6/issues/2044, when both number of packets arriving and size of the packets are large, statds_exporter starts to drop UDP packets because processing speed cannot catch the packet arrival speed
In the past, I implemented similar UDP packet processing application in Java and best practice was there to read packet in one thread and process packets in another thread(s), therefore I introduced similar logic here: I added a queue / channel (chan []byte) so that the goroutine reading the packets from UDP socket can enqueue them in order to minimize time spent per packet and packets are processed in another goroutine which reads from the …

Performance improvement - process udp packets in separate goroutine in order to minimize packet drops

---

pkg/exporter/exporter.go
pkg/exporter/exporter_test.go
pkg/mapper/mapping.go

When a label is assigned in mappings that already exists, it will be replaced. This PR introduces a `honor_labels` parameter. When this parameter is set to true, it will preserve the original value of the label.

Add configuration for keeping original labels in mappings

---

README.md

I have no idea if it is even up to date. The README file was too large to fit Docker Hub's limitations; this removal brings us just under the [25KB limit](https://github.com/docker/hub-feedback/issues/238).

Remove `--help` output from README

---

pkg/line/line.go
pkg/line/line_test.go

This PR aims to add the ability for statsd exporter to receive [DogStatsD extended aggregation metrics](https://github.com/DataDog/datadog-go?tab=readme-ov-file#extended-aggregation). It is a feature I requested in Issue #557 and I wanted to try to implement it myself following the in-issue commented advice from @glightfoot. 
When DogStatsD has extended aggregation enabled, instead of sending:
```
my_distribution_metric:21|d|#all,my,tags
my_distribution_metric:43.2|d|#all,my,tags
my_distribution_metric:1657|d|#all,my,tags
```
it sends
```
my_distribution_metric:21:43.2:1657|d|#all,my,tags
```
This PR updates the `LineToEvents` function in the specific case of more than one `:` left of the initial `|`. If so, assume it is an extended aggregation line, convert it back into its multi-line …

Add DogStatsD extended aggregation support

---

.golangci.yml

When linting, govet complains about the deprecated `check-shadowing` setting.
Replace it with enabling all currently passing linters. This excludes only
`fieldalignment`.

Enable all govet linters except fieldalignment

---

MAINTAINERS.md

Pedro runs [one of the largest statsd-exporter
installations](https://promcon.io/2023-berlin/talks/taming-the-tsunami-low-latency-ingestion-of-push-based-metrics-in-prometheus/)
and is a natural fit for this 😀
Thank you Pedro for agreeing to help out!

Add Pedro Tanaka as co-maintainer

---

main.go
pkg/exporter/exporter.go
pkg/exporter/exporter_test.go

This is a modification we did to our internal version of the statsd-exporter and actually makes this metric actionable, so you can track down which metrics are problematic and fix them at the source (application code) or filter them out in the statsd exporter configuration.
If cardinality is a concern for other users, I can try enabling this behind a feature flag, and report a constant metric name if we dont want to track it.

Keep track of metric names on the metric statsd_exporter_events_conflict_total

---

README.md
config.example.yml

Take the existing starter configuration that we had buried in the middle of the
README. Slightly modernize it: disable glob mapping ordering by default, and set
the default # of native histogram buckets to 160, matching [defaults in
OpenTelemetry and the recommendation in Mimir](https://grafana.com/docs/mimir/latest/configure/configure-native-histograms-ingestion/#configure-native-histograms-per-tenant).
Add an example of overriding the default native histogram bucket factor.

Extract and modernize starter configuration
