prometheus/statsd_exporter

bridge.go
@juliusv 
Depends on https://github.com/prometheus/client_golang/pull/45
=> Adjust call syntax of Register to the new client_golang.

README.md, mapper_test.go
See http://golang.org/pkg/regexp/#Regexp.Expand
=> Correct example, need to specify variables like in bash.

bridge.go
=> Move from client_golang/model to common/model

.gitignore, CHANGELOG.md, Makefile, Makefile.COMMON
Update build
* Add `.gitignore`.
* Update Makefile.COMMON from prometheus/utils.
Release 0.2.0
* Update Makefile.
* Add CHANGELOG.md.
=> Update for 0.2.0 release

README.md, bridge_test.go, exporter.go
=> Dogstats extensions squashed

bridge_test.go, exporter.go
=> Added increment/decrement support to Gauges

README.md, mapper.go, mapper_test.go
Hi.  This is handy and missing.  Hope it is acceptable @juliusv.
=> Allow comments in mapping files

MAINTAINERS.md
=> Change maintainership to Matthias

mapper.go, mapper_test.go
rebase of #96 since the whole old config format is gone now.
=> Fix matching empty statsd metric components

README.md, exporter_test.go, mapper_test.go
Following up on #102 and #97 sent me down a rabbit hole of trying to understand what actually is the expected behaviour. This PR adds tests to confirm the current behaviour, and adjusts the documentation to actually match that.
=> Fix and test examples in the README

README.md, exporter.go, mapper.go, mapper_test.go
fixes #90
I had to modify the tests a bit for this to work as expected. I'm not 100% that the tests are correct.
=> Allow using name in mapping rather than 'name' label

README.md, action.go, exporter.go, mapper.go, mapper_test.go
As discussed in #79 this adds an "action" to each match which defaults to "map".
=> Add drop action for matches

README.md, exporter.go, mapper.go, mapper_test.go
Hi folks,
I'm opening this PR as an attempt to get this feature merged since I need it in one of my projects. It was originally implemented by @drawks at the PR #89. I've reimplemented the same feature on top of the most recent version of the master branch and added a few test cases.
I hope this helps.
=> Allow for dynamic metric name

.travis.yml, Makefile, Makefile.common, main.go
=> Use Makefile.common from Prometheus

CHANGELOG.md
for clickability.
Signed-off-by: Matthias Rampke <mr@soundcloud.com>
=> Make all the PR references in CHANGELOG links

main.go
This commit also removes the deprecated -statsd.listen-address flag. Switching to kingpin is a breaking change in that flags now start with two hyphens (e.g. --statsd.listen-udp), and thus a good time to remove deprecated flags.
Fixes #111.
=> Switch to kingpin for flag handling

CHANGELOG.md
to be in line with the Prometheus [release guidelines](https://github.com/prometheus/prometheus/wiki/HOWTO-cut-a-new-release#prepare-your-release
).
=> Changelog: use ENHANCEMENT

README.md
1. Configuration file extension changed from .conf to .yml
2. Added missing dash (-) in statsd-exporter inputs
=> Fixed docker run command

telemetry.go
See also the related discussion at #160
=> Register eventsUnmapped counter

exporter.go
It's idiomatic in go to keep code indentation due to nested loops to a
minimum. Decoupling the events handling function into its own function
makes it easier to read the code and test the behavior in isolation of
the channel handling. It's now also easily possible to process events
in parallel without having to touch actual business code.
Signed-off-by: Tobias Schmidt <tobidt@gmail.com>
=> Break out event handling into its own function

README.md
@Matthias Rampke
Signed-off-by: dongwenjuan <dong.wenjuan@zte.com.cn>
=> fix the format of code-block in README

Makefile, Makefile.common, exporter.go, exporter_test.go, main.go, pkg/mapper/fsm/fsm.go, pkg/mapper/mapper.go
=> Travis CI: add staticcheck target

README.md
Closes: https://github.com/prometheus/statsd_exporter/issues/180
Signed-off-by: Ben Kochie <superq@gmail.com>
=> Mention automatic reloading in the README.

exporter_test.go
Replaces #222 
Signed-off-by: Benno Rice <benno@jeamland.net>
=> Add a test for adding labels from mapper configuration.

main.go
Fixes crash from #251 according to the test for the issue there.
@matthiasr
=> Add event handler for Unixgram

README.md
=> Update use_ms note for dogstatsd client

bridge_test.go, exporter.go
This is an attempted fix for #250
=> Support sampling factor for all statsd metric types

CHANGELOG.md, README.md, pkg/mapper/mapper_test.go
This should fix #274 and also some tests with good/bad yaml to verify this behaviour.
=> Updated docs and added good/bad example yaml

CHANGELOG.md, pkg/mapper/mapper_cache.go
cf. https://github.com/prometheus/statsd_exporter/pull/282#issuecomment-573031514
Signed-off-by: Matthias Rampke <mr@soundcloud.com>
=> Make mapper cache metric names more specific

pkg/event/event.go
* Set Flush Interval on EventQueue
@matthiasr
=> Set Flush Interval on EventQueue

main.go, pkg/event/event.go, pkg/listener/listener.go
* Log ingested lines
* Resolves #299 
@matthiasr
=> Log Ingested Lines

CHANGELOG.md, README.md
Update the README to reflect #314. Add an entry to the changelog
with extended compatibility notes.
@glightfoot did I misrepresent anything?
=> Changelog and documentation update for #314

.circleci/config.yml, .promu.yml
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
=> Bump go to 1.15

main.go
=> add healthcheck endpoint

pkg/exporter/exporter.go
Fixes https://github.com/prometheus/statsd_exporter/issues/330
=> Use an interface for Registry so we may have alternate implementations

main.go
Don't return empty responses to the lifecycle api and use the existing signals chan to quit instead of os.exit
Fixes #358 @matthiasr 
```
$ curl -X POST  http://localhost:9102/-/quit 
Requesting termination... Goodbye!%
$ echo $? 
0
```
=> Don't return empty responses to lifecycle api requests

pkg/mapper/mapper.go, pkg/mapper/mapper_test.go
See https://github.com/prometheus/statsd_exporter/issues/380
@matthiasr I don't do any Go development so not sure if there's anything else to consider here 😅 
Thanks!
=> allow multiple dashes in StatsD metric names

.circleci/config.yml, .promu.yml, go.mod, go.sum
* Update to Go 1.17.
* Update Go mods.
Signed-off-by: SuperQ <superq@gmail.com>
=> Update build for Go 1.17

README.md
Recommend running the exporter as a sidecar, now that the relay feature
makes this easy.
Re-order the overview section to put the final state first, then explain
transition and try-out options.
=> Update transition scenarios

README.md
This PR documents some doubts I had in the issue #438 and therefore closes it.
By using the approach I documented here, I was able to achieve the behavior
I described in #438.
=> Adding documentation about special regex match group

bridge_test.go, pkg/exporter/exporter_test.go
Validate the behavior for relative gauge events as per [the statsd type metric type documentatoin](https://github.com/statsd/statsd/blob/master/docs/metric_types.md#gauges).
Reaffirms #523.
=> Add more tests for gauge increment/decrement

.golangci.yml
Enable all rules from staticcheck by default and disable not compliant rules
=> chore: enable all rules from staticcheck
